blueprint:
  name: Availability check label (with last_reported threshold & unavailable state)
  description: Exécute des actions aux heures choisies si des entités avec un label spécifique sont "unavailable" ou n'ont pas été mises à jour depuis un certain temps.
  domain: automation
  source_url: https://github.com/francoiskha/availability-check/blob/main/availability_check_label.yaml
  input:
    time1:
      name: Heure 1
      description: Heure 1 de test (pas d'exécution si "00:00")
      default: '10:00:00'
      selector:
        time: {}
    time2:
      name: Heure 2
      description: Heure 2 de test (pas d'exécution si "00:00")
      default: 00:00:00
      selector:
        time: {}
    time3:
      name: Heure 3
      description: Heure 3 de test (pas d'exécution si "00:00")
      default: 00:00:00
      selector:
        time: {}
    time4:
      name: Heure 4
      description: Heure 4 de test (pas d'exécution si "00:00")
      default: 00:00:00
      selector:
        time: {}
    time5:
      name: Heure 5
      description: Heure 5 de test (pas d'exécution si "00:00")
      default: 00:00:00
      selector:
        time: {}
    selector:
      name: Label pour surveillance
      description: Label permettant d'identifier les entités à surveiller
      default: ''
    last_reported_max_minutes :
      name: seuil d'alerte si entité non mis à jour
      description: La durée en minutes après laquelle on déclenche une alerte si la valeur n'a pas été mise à jour
      default: 90
      selector:
          number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
          mode: box
    actions:
      name: Actions
      description: Notifications ou autre à exécuter. {{entities}} dans message sera remplacé par la liste des entités non disponibles.
      selector:
        action: {}

variables:
  selector: !input selector
  last_reported_max_minutes: !input last_reported_max_minutes
  time1: !input time1
  time2: !input time2
  time3: !input time3
  time4: !input time4
  time5: !input time5
  entities: >
    {% set result = namespace(entities=[]) %}
    {% set entity_list = label_entities(selector) %}
    {% for item in entity_list %}
      {% for state in states | selectattr('entity_id', 'eq', item) %}
        {% if (now() - state.last_reported > timedelta(hours = 0, minutes = last_reported_max_minutes)) or ( not has_value(state.entity_id) ) %}
          {% set result.entities = result.entities + [state.name if state.name else state.entity_id] %}
        {% endif %}
      {% endfor %}
    {% endfor %}
    {{ result.entities | unique | sort(attribute='entity_id') | join(', ') }}

trigger:
- platform: time
  at: !input time1
- platform: time
  at: !input time2
- platform: time
  at: !input time3
- platform: time
  at: !input time4
- platform: time
  at: !input time5

condition:
- condition: and
  conditions:
    - condition: template
      value_template: '{{ time1 != "00:00:00" or time2 != "00:00:00" or time3 != "00:00:00" or time4 != "00:00:00" or time5 != "00:00:00" }}'
    - condition: template
      value_template: '{{ entities != "" }}'

action:
- choose: []
  default: !input actions

mode: single
max_exceeded: silent